apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-tls-example.name" . }}-certificates-secret
  labels:
  {{- include "redis-tls-example.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ ( include "redis-tls-example.generate-certificates" . ) | indent 2 }}
